#!/usr/bin/env bash
set -e

ZIP=0
if [[ "${1:-}" == "-zip" ]]; then
    ZIP=1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$SCRIPT_DIR/mlTradingArchitecture"
OUT_CORE="$OUT_DIR/mlTradingArchitectureCore.h"
OUT_FULL="$OUT_DIR/mlTradingArchitecture.h"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR/vendor/glfw/include" "$OUT_DIR/vendor/glfw/lib"
cp -r "$SCRIPT_DIR/vendor/glfw/include/." "$OUT_DIR/vendor/glfw/include/"
cp "$SCRIPT_DIR/vendor/glfw/lib/"* "$OUT_DIR/vendor/glfw/lib/"

# core: just the engine - Engine/Request/Response, simulateTradeStep, the
# CostFn hook (defaultCostFn charges only the sampled transaction cost),
# CloseConditionPipeline, and tooling. No QModel (bring your own
# action-selection) and no costFactorization.h's RiskCostModel (bring your own
# CostFn, or none at all).
CORE_FILES=(
    "$SCRIPT_DIR/src/tooling/dollarDeltaToPoints.h"
    "$SCRIPT_DIR/src/tooling/matrices.h"
    "$SCRIPT_DIR/src/tooling/agentParameter.h"
    "$SCRIPT_DIR/src/mlConfig.h"
    "$SCRIPT_DIR/src/tooling/costFn.h"
    "$SCRIPT_DIR/src/dataRequestHandler.h"
    "$SCRIPT_DIR/src/pipeline.h"
    "$SCRIPT_DIR/src/models/conditions.h"
)

# full: everything in core, plus QModel (the Q-learning/bandit agent) and
# costFactorization.h's RiskCostModel (a built-in, swappable CostFn
# implementation - one option among others, not a dependency of core).
FULL_FILES=(
    "$SCRIPT_DIR/src/tooling/dollarDeltaToPoints.h"
    "$SCRIPT_DIR/src/tooling/matrices.h"
    "$SCRIPT_DIR/src/tooling/agentParameter.h"
    "$SCRIPT_DIR/src/mlConfig.h"
    "$SCRIPT_DIR/src/tooling/costFn.h"
    "$SCRIPT_DIR/src/dataRequestHandler.h"
    "$SCRIPT_DIR/src/tooling/costFactorization.h"
    "$SCRIPT_DIR/src/pipeline.h"
    "$SCRIPT_DIR/src/models/conditions.h"
    "$SCRIPT_DIR/src/models/QModel.h"
)

# Writes one standalone amalgamated header to $1, inlining azbacktest.h plus
# the dependency-ordered file list passed in $2.. - each output is meant to be
# usable entirely on its own, so both variants repeat the azbacktest.h inline.
write_amalgamation() {
    local out="$1"
    shift
    local files=("$@")

    {
        echo "// ML Trading Architecture amalgamation, auto-generated by amalgamate.sh"
        echo "// Do not edit directly, modify the source files in src/ instead"
        echo "// (unless you know what you're doing, of course)"
        echo ""
        echo "#pragma once"
        echo ""
    } > "$out"

    # azbacktest.h first - everything below depends on it. It's already its own
    # amalgamation (imgui/implot/glfw headers + AZBacktest's own src inlined), so
    # this just folds that whole single header in, the same way AZBacktest folds
    # imgui.h/implot.h into itself rather than leaving them as separate #includes.
    echo "" >> "$out"
    echo "// ---- vendor/azbacktest.h ----" >> "$out"
    sed -E '/^#pragma once/d' "$SCRIPT_DIR/vendor/azbacktest.h" >> "$out"

    for f in "${files[@]}"; do
        rel="${f#$SCRIPT_DIR/}"
        echo "" >> "$out"
        echo "// ---- $rel ----" >> "$out"
        # strip #pragma once and local #include "..." lines, keep everything else -
        # every local include here is one of azbacktest.h or a file already in
        # this same file list, both already inlined above/earlier in the list
        sed -E '/^#pragma once/d; /^[[:space:]]*#include[[:space:]]*"/d' "$f" >> "$out"
    done

    echo "wrote $out"
}

write_amalgamation "$OUT_CORE" "${CORE_FILES[@]}"
write_amalgamation "$OUT_FULL" "${FULL_FILES[@]}"

if [[ $ZIP -eq 1 ]]; then
    ZIP_PATH="$SCRIPT_DIR/mlTradingArchitecture.zip"
    rm -f "$ZIP_PATH"
    if command -v zip >/dev/null 2>&1; then
        (cd "$SCRIPT_DIR" && zip -rq "$ZIP_PATH" mlTradingArchitecture)
    else
        # git-bash/MSYS doesn't ship zip by default, fall back to PowerShell.
        # The .h files were just written moments ago and can still be held by a
        # transient lock (e.g. antivirus scanning a freshly-created multi-MB
        # file) - Compress-Archive only warns and keeps going on a per-file
        # lock unless told to stop, silently producing an incomplete archive,
        # so force it to fail loudly (-ErrorAction Stop) and retry past it.
        WIN_SRC="$(cygpath -w "$OUT_DIR")"
        WIN_DST="$(cygpath -w "$ZIP_PATH")"
        ZIP_OK=0
        for attempt in 1 2 3 4 5; do
            if powershell.exe -NoProfile -Command "Compress-Archive -Path '$WIN_SRC' -DestinationPath '$WIN_DST' -Force -ErrorAction Stop"; then
                ZIP_OK=1
                break
            fi
            echo "zip attempt $attempt failed (likely a transient file lock), retrying..." >&2
            sleep 1
        done
        if [[ $ZIP_OK -eq 0 ]]; then
            echo "failed to zip after 5 attempts" >&2
            exit 1
        fi
    fi
    echo "wrote $ZIP_PATH"
fi
